version: '3'

services:
  bucket-api:
    build:
      context: ./bucket-api
      args:
        - START_COMMAND=$BUCKET_API_START_COMMAND
    container_name: bucket-api
    environment:
      - HOST_DATA_FOLDER=$HOST_DATA_FOLDER
      
      - NODE_ENV=$NODE_ENV
      - DEV_USER=$DEV_USER
      - DEV_TOKEN=$DEV_TOKEN
      - DPI_URL=$DPI_URL
      
      - HTTP_HOST=$HTTP_HOST
      - HTTP_PORT=$HTTP_PORT
      - HTTP_SECURED=$HTTP_SECURED
      - HTTP_BASE_URL=$HTTP_BASE_URL
      
      - MQTT_HOST=$MQTT_HOST
      - MQTT_PORT=$MQTT_PORT
      - MQTT_CLIENT_ID=$MQTT_CLIENT_ID
      - MQTT_CLIENT_USER=$MQTT_CLIENT_USER
      - MQTT_CLIENT_PASS=$MQTT_CLIENT_PASS

      - KEY_PATH=$KEY_PATH
      - CERT_PATH=$CERT_PATH
      
      - POSTGRES_HOST=$BUCKET_POSTGRES_HOST
      - POSTGRES_USER=$BUCKET_POSTGRES_USER
      - POSTGRES_PASSWORD=$BUCKET_POSTGRES_PASSWORD
      - POSTGRES_PORT=$BUCKET_POSTGRES_PORT
      - POSTGRES_DB=$BUCKET_POSTGRES_DB
      - POSTGRES_LOGGING=$BUCKET_POSTGRES_LOGGING

      - INFLUXDB_HOST=$BUCKET_INFLUXDB_HOST
      - INFLUXDB_DB=$BUCKET_INFLUXDB_DB

      - GRAFANA_API_URL=$GRAFANA_API_URL
      - GRAFANA_API_KEY=$GRAFANA_API_KEY
      - GRAFANA_USER=$GRAFANA_USER
      - GRAFANA_PASS=$GRAFANA_PASS

      - OAUTH2_INTROSPECT_URL=$OAUTH2_INTROSPECT_URL
      - OAUTH2_TOKEN_URL=$OAUTH2_TOKEN_URL
      - OAUTH2_REVOKE_URL=$OAUTH2_REVOKE_URL
      - OAUTH2_AUTH_URL=$OAUTH2_AUTH_URL
      - OAUTH2_PROFILE_URL=$OAUTH2_PROFILE_URL
      - OAUTH2_REDIRECT_URL=$OAUTH2_REDIRECT_URL
      - OAUTH2_CLIENT_ID=$OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$OAUTH2_CLIENT_SECRET
      - OAUTH2_SCOPE=$OAUTH2_SCOPE
      - OAUTH2_HYDRA_ADMIN_URL=$OAUTH2_HYDRA_ADMIN_URL

      - ACP_URL=$ACP_URL
    depends_on:
      - bucket-postgres
      - bucket-influxdb
    volumes:
      - ./certs:/etc/certs
      - $HOST_DATA_FOLDER:$HOST_DATA_FOLDER
    ports:
    #   - $HTTP_PORT:$HTTP_PORT
      - $MQTT_PORT:$MQTT_PORT

  bucket-ui:
    build:
      context: ./bucket-ui
      args:
        - BASE_HREF=$BUCKET_UI_BASE_HREF
        - DEPLOY_URL=$BUCKET_UI_DEPLOY_URL
        - CONFIGURATION=$BUCKET_UI_CONFIGURATION
    container_name: bucket-ui
    environment:
     - NGINX_HOST=$BUCKET_UI_HOST
     - NGINX_PORT=$BUCKET_UI_PORT
    # ports:
    #  - $BUCKET_UI_PORT:$BUCKET_UI_PORT

  bucket-postgres:
    image: postgres:9.6
    container_name: bucket-postgres
    environment:
      - POSTGRES_USER=$BUCKET_POSTGRES_USER
      - POSTGRES_PASSWORD=$BUCKET_POSTGRES_PASSWORD
      - POSTGRES_PORT=$BUCKET_POSTGRES_PORT
      - POSTGRES_DB=$BUCKET_POSTGRES_DB
    volumes:
      - $HOST_DATA_FOLDER/bucket-postgres:/var/lib/postgresql/data
    ports:
      - $BUCKET_POSTGRES_PORT:$BUCKET_POSTGRES_PORT

  bucket-influxdb:
    image: influxdb:1.8
    container_name: bucket-influxdb
    volumes:
      - $HOST_DATA_FOLDER/bucket-influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      - INFLUXDB_DB=$BUCKET_INFLUXDB_DB
      - INFLUXDB_ADMIN_ENABLED=true

networks: 
  default:
      external:
        name: dcd-net