version: '3'

services:
  bucket-api:
    # image: datacentricdesign/bucket-api:release-0.0.12
    build:
      context: ./bucket-api
    container_name: bucket-api
    environment:
      - HOST_DATA_FOLDER=$HOST_DATA_FOLDER

      - JWT_SECRET=TEST
      
      - NODE_ENV=$NODE_ENV
      - DEV_USER=dcd:persons:test@test.test
      - DEV_TOKEN=tester-token
      
      - HTTP_HOST=$HTTP_HOST
      - HTTP_PORT=$HTTP_PORT
      - HTTP_SECURED=$HTTP_SECURED
      - HTTP_BASE_URL=$HTTP_BASE_URL
      
      - MQTT_HOST=$MQTT_HOST
      - MQTT_PORT=$MQTT_PORT
      - MQTT_CLIENT_ID=$MQTT_CLIENT_ID
      - MQTT_CLIENT_USER=$MQTT_CLIENT_USER
      - MQTT_CLIENT_PASS=$MQTT_CLIENT_PASS

      - KEY_PATH=$KEY_PATH
      - CERT_PATH=$CERT_PATH
      
      - POSTGRES_HOST=$BUCKET_POSTGRES_HOST
      - POSTGRES_USER=$BUCKET_POSTGRES_USER
      - POSTGRES_PASSWORD=$BUCKET_POSTGRES_PASSWORD
      - POSTGRES_PORT=$BUCKET_POSTGRES_PORT
      - POSTGRES_DB=$BUCKET_POSTGRES_DB
      - POSTGRES_LOGGING=$BUCKET_POSTGRES_LOGGING

      - INFLUXDB_HOST=$BUCKET_INFLUXDB_HOST
      - INFLUXDB_DB=$BUCKET_INFLUXDB_DB

      - OAUTH2_INTROSPECT_URL=$OAUTH2_INTROSPECT_URL
      - OAUTH2_TOKEN_URL=$OAUTH2_TOKEN_URL
      - OAUTH2_REVOKE_URL=$OAUTH2_REVOKE_URL
      - OAUTH2_AUTH_URL=$OAUTH2_AUTH_URL
      - OAUTH2_PROFILE_URL=$OAUTH2_PROFILE_URL
      - OAUTH2_REDIRECT_URL=$OAUTH2_REDIRECT_URL
      - OAUTH2_CLIENT_ID=$OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$OAUTH2_CLIENT_SECRET
      - OAUTH2_SCOPE=$OAUTH2_SCOPE

      - ACP_URL=http://localhost:4466
    ports:
      - 8889:8080
    depends_on:
      - bucket-postgres
      - bucket-influxdb

  bucket-ui:
    # image: datacentricdesign/bucket-ui:release-0.0.12
    build:
      context: ./bucket-ui
    container_name: bucket-ui
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=8888
    ports:
      - 8888:8888

  bucket-postgres:
    image: postgres:9.6
    container_name: bucket-postgres
    environment:
      - POSTGRES_USER=$BUCKET_POSTGRES_USER
      - POSTGRES_PASSWORD=$BUCKET_POSTGRES_PASSWORD
      - POSTGRES_PORT=$BUCKET_POSTGRES_PORT
      - POSTGRES_DB=$BUCKET_POSTGRES_DB
    volumes:
      - $HOST_DATA_FOLDER/bucket-postgres:/var/lib/postgresql/data
    ports:
      - $BUCKET_POSTGRES_PORT:$BUCKET_POSTGRES_PORT

  bucket-influxdb:
    image: influxdb
    container_name: bucket-influxdb
    volumes:
      - $HOST_DATA_FOLDER/bucket-influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      - INFLUXDB_DB=$BUCKET_INFLUXDB_DB
      - INFLUXDB_ADMIN_ENABLED=true

networks: 
  default:
      external:
        name: dcd-net