version: '3'

services:
  bucket-api:
    build: 
        context: ./bucket-api
    container_name: bucket-api
    environment: 
      - HOST_DATA_FOLDER=$HOST_DATA_FOLDER

      - JWT_SECRET=TEST
      
      - NODE_ENV=$NODE_ENV
      - DEV_USER=dcd:persons:test@test.test
      - DEV_TOKEN=tester-token
      
      - HTTP_HOST=$HTTP_HOST
      - HTTP_PORT=$HTTP_PORT
      - HTTP_SECURED=$HTTP_SECURED
      - HTTP_BASE_URL=$HTTP_BASE_URL
      
      - MQTT_HOST=$MQTT_HOST
      - MQTT_PORT=$MQTT_PORT
      - MQTT_CLIENT_ID=$MQTT_CLIENT_ID
      - MQTT_CLIENT_USER=$MQTT_CLIENT_USER
      - MQTT_CLIENT_PASS=$MQTT_CLIENT_PASS

      - KEY_PATH=$KEY_PATH
      - CERT_PATH=$CERT_PATH
      
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_LOGGING=$POSTGRES_LOGGING

      - INFLUXDB_HOST=$INFLUXDB_HOST
      - INFLUXDB_DB=$INFLUXDB_DB

      - OAUTH2_INTROSPECT_URL=https://dwd.tudelft.nl/oauth2/introspect
      - OAUTH2_TOKEN_URL=https://dwd.tudelft.nl/oauth2/token
      - OAUTH2_REVOKE_URL=https://dwd.tudelft.nl/oauth2/revoke
      - OAUTH2_AUTH_URL=https://dwd.tudelft.nl/oauth2/auth
      - OAUTH2_PROFILE_URL=https://dwd.tudelft.nl/userinfo
      - OAUTH2_REDIRECT_URL=http://localhost:8080/test/auth/callback
      - OAUTH2_CLIENT_ID=clients:test-client-id
      - OAUTH2_CLIENT_SECRET=test-client-secret
      - OAUTH2_SCOPE=offline openid profile dcd:things

      - ACP_URL=http://localhost:4466

  bucket-ui:
    build:
        context: ./bucket-ui
    container_name: bucket-ui
    image: datacentricdesign/bucket-ui:release-0.0.1
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80

  bucket-postgres:
    image: postgres:9.6
    container_name: bucket-postgres
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - $HOST_DATA_FOLDER/postgresql:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT

  bucket-influxdb:
    image: influxdb
    container_name: bucket-influxdb
    volumes:
      - $HOST_DATA_FOLDER/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      - INFLUXDB_DB=$INFLUXDB_DB
      - INFLUXDB_ADMIN_ENABLED=true

networks: 
  default:
      external:
        name: dcd-net